### ISSUE TITLE
Doesn't work on Fb Messenger/Instagram in-app browser on Android device

### ISSUE THREAD

**Issue by shaagi** [feross/clipboard-copy#37]
So i tried it in dev and it worked great. Worked fine if I was using iOS device. Works fine if it's google chrome and NOT an in-app browser. On Android though, I opened the webpage of my angular 7 app using fb messenger, so it opened using facebook's in-app browser and when I trigger the copy function it caught the below error:

_NotAllowedError: Write permission denied._

Not sure if this falls in your domain but thought I should mention it. I'm a beginner programmer so please let me know which details need to be provided.

My typescript code:

```
getShareLink() {
    
    copy(this.inviteUrl)
      .then(data => {
     
        this.successMessage = data;
       
        return this.toastr.success('Link copied to clipboard');
      }).catch(err => {
        this.failMessage = err;
        console.log(err);
    });
  }
```

this.failMessage on the front end was _NotAllowedError: Write permission denied._

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it. If you would like to see it implemented, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
