### ISSUE TITLE
Not working inside cross-domain iframe

### ISSUE THREAD

**Issue by petedol87** [feross/clipboard-copy#41]
Hello, 

Thanks for this nice package.

It seems like the copy doesn't work when the page is loaded into a cross-domain iframe, although the promise returns success. Tested in all major desktop/mobile browsers.

**Comment by hamaron** [comment]
I came across the same issue, digged into it and it turned out that it was actually the browser which blocked
a write operation to the clipboard.

I saw this error message on the console when I tried to copy a text:
`DOMException: The Clipboard API has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.`

In order to avoid this issue, you need to pass the value `clipboard-write` to the `allow` attribute in your iframe like so:
```
<iframe ... allow="clipboard-write"></iframe>
```

**Comment by petedol87** [comment]
@hamaron I can confirm you are right, thanks! 

Although this attribute value is not fully supported yet, I tested and it seems like it's not working in any mobile browser (iOS or Android).

**Comment by hklee93** [comment]
@petedol87 Hi, I'm trying to use the library within the webview both on iOS and Android. When I tested, I noticed that copying to clipboard doesn't work on the Android emulator while it works on the iOS simulator. I was wondering if there's anything I'm missing, or is that somewhat related to this OP?

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
