### ISSUE TITLE
can i use it in IE8, chrome,and firefox ?

### ISSUE THREAD

**Issue by yvonnegithub** [feross/clipboard-copy#8]

**Comment by LinusU** [comment]
Chrome and Firefox are supported.

IE support was merged in #9, but I'm not sure which version.

We should check and add it to the readme, PRs welcome 🙌

**Comment by feross** [comment]
The point of this library (versus other ones mentioned in the readme) is to be lightweight. We only support modern browsers. I was okay with adding IE support in #9 since it didn't add new lines of code or hacks.

I'll test in IE11 just to confirm it works, add that to the readme, and then close this issue.

**Comment by feross** [comment]
Great, confirmed it works in IE11. ✨

Let's not support anything lower, the other libraries already work for that!
